### PR TITLE
`wback` subset01 implementation

### PR DESCRIPTION
**Pull request by poorna2152**

### CODE REVIEW

**Comment by poorna2152** [comment]
Following tests are failing at the moment,
- [assign8-v.bal](https://github.com/poorna2152/nballerina/blob/main/compiler/testSuite/01-function/assign8-v.bal): This has an int array. Not sure whether arrays are in subset01.
- [add2-p.bal](https://github.com/poorna2152/nballerina/blob/main/compiler/testSuite/01-int/add2-p.bal), [div1-p.bal](https://github.com/poorna2152/nballerina/blob/main/compiler/testSuite/01-int/div1-p.bal), [div3-p.bal](https://github.com/poorna2152/nballerina/blob/main/compiler/testSuite/01-int/div3-p.bal), [rem1-p.bal](https://github.com/poorna2152/nballerina/blob/main/compiler/testSuite/01-int/rem1-p.bal): These tests are failing since they are throwing exceptions and exception handling is not implemented in from the WASM side yet.
- [rel-v.bal](https://github.com/poorna2152/nballerina/blob/main/compiler/testSuite/01-nil/rel-v.bal): This test fails due to it calling println function with a i32(boolean) value than a i64 which it expects.

**Comment by manuranga** [comment]
Just for the record:
[assign8-v.bal](https://github.com/poorna2152/nballerina/blob/main/compiler/testSuite/01-function/assign8-v.bal) and [rel-v.bal](https://github.com/poorna2152/nballerina/blob/main/compiler/testSuite/01-nil/rel-v.bal) are there in the subset 1 by a mistake.

Need to fix `p` cases by throwing an exception. Any function that blows up wasm execution should work, no need to wait for exceptions proposal form wasm.

**Comment by poorna2152** [comment]
[equal-v.bal](https://github.com/poorna2152/nballerina/blob/main/compiler/testSuite/01-misc/equal-v.bal) failing: function return type set to `any` in this testcase.

**Comment by poorna2152** [comment]
`Expression` record type holds an array of tokens instead of a string. This tokens are later joined in creating the `wat` file. The sub types of `Expression` `WasmBlock`, `WasmLoop`, `If` and `Break` in the previous code were removed.

**Pull request closed without merging**
